#define WIFI_SSID "***"
#define WIFI_PASS "***"

#define WIFI_HOST "wetterstation-nano"
#define WIFI_SERVER_PORT 80

#define I2C_BME280 0x77

#define OUTPUT_REMOTE_IP "***"
#define OUTPUT_REMOTE_PORT 0
#define OUTPUT_REMOTE_PATH "***"

#define CALIBRATION_COMFORT_TEMPERATURE_MEAN 17.0
#define CALIBRATION_COMFORT_HUMIDITY_MEAN 55.0
#define CALIBRATION_TEMP_HOUSING_CORRECTION_OFFSET -0.5
#define CALIBRATION_COMFORT_TEMPERATURE_COEFF 4.6
#define CALIBRATION_COMFORT_HUMIDITY_COEFF 10

#define STATIONINFO_NAME "Innen Nano"